/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*     It creates AppUI & takes care of data model of application.
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/



#ifndef __ZMobileTrackerDOCUMENT_H__
#define __ZMobileTrackerDOCUMENT_H__

// INCLUDES
#include <akndoc.h>
#include "ZMobileTrackerengine.h"

   
// FORWARD DECLARATIONS
class CEikAppUi;
class CZMobileTrackerInformationAndSettings;


// CLASS DECLARATION

/**
* CZMobileTrackerDocument application class.
* An instance of class CZMobileTrackerDocument is the Document part of the
* AVKON application framework for the NAC example application.
*/
class CZMobileTrackerDocument : public CAknDocument
    {
    public: // Types
        typedef CZMobileTrackerEngine::TBoard TBoard;

    public: // Constructors and destructor

        /**
        * NewL.
        * Two-phased constructor.
        * Construct a CZMobileTrackerDocument for the AVKON application aApp
        * using two phase construction, and return a pointer
        * to the created object.
        * @param aApp Application creating this document.
        * @return A pointer to the created instance of CZMobileTrackerDocument.
        */
        static CZMobileTrackerDocument* NewL(CEikApplication& aApp);

        /**
        * ~CZMobileTrackerDocument
        * Virtual Destructor.
        */
        virtual ~CZMobileTrackerDocument();

    public: // New functions

        /**
        * SetObserver.
        * @param aObserver.
        */
        void SetObserver(CZMobileTrackerEngine::MObserver* aObserver);

        /**
        * NewGame.
        */
        void NewGame();

        /**
        * CanMove.
        * @return.
        */
        TBool CanMove() const;

        /**
        * MakeHumanMove.
        * @param aRow.
        * @param aColumn.
        * @return.
        */
        TBool MakeHumanMove(TInt aRow, TInt aColumn);

        /**
        * MakeComputerMove.
        * @return.
        */
        TBool MakeComputerMove();

        /**
        * InformationAndSettings.
        * @return.
        */
        CZMobileTrackerInformationAndSettings& InformationAndSettings();

        /**
        * InformationAndSettings.
        * @return.
        */
        const CZMobileTrackerInformationAndSettings& InformationAndSettings() const;

        /**
        * SaveSettingsAndInformationL.
        */ 
        void SaveSettingsAndInformationL();

        /**
        * Board.
        * @return.
        */
        const TBoard& Board() const;

    private: // Functions from base classes

        /**
        * CreateAppUiL
        * From CEikDocument, CreateAppUiL.
        * Create a CZMobileTrackerAppUi object and return a pointer to it.
        * The object returned is owned by the Uikon framework.
        * @return Pointer to created instance of AppUi.
        */
        CEikAppUi* CreateAppUiL();

    private: // Constructors

        /**
        * CZMobileTrackerDocument.
        * C++ default constructor.
        * @param aApp Application creating this document.
        */
        CZMobileTrackerDocument(CEikApplication& aApp);

        /**
        * ConstructL
        * 2nd phase constructor.
        */
        void ConstructL();

    private: // Data
        CZMobileTrackerInformationAndSettings* iSettings;
        CZMobileTrackerEngine* iEngine;
		
    };

#endif // __ZMobileTrackerDOCUMENT_H__

// End of File
