/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*	  It creates view, control command handling & user interactions. 
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/



#ifndef __ZMobileTrackerAPPUI_H__
#define __ZMobileTrackerAPPUI_H__

// INCLUDES
#include <aknviewappui.h>
class CZMobileTrackerView;
class CZMobileTrackerSettingsView;


// CLASS DECLARATION
/**
* CZMobileTrackerAppUi application UI class.
* Interacts with the user through the UI and request message processing
* from the handler class
*/
class CZMobileTrackerAppUi : public CAknViewAppUi
    {
    public: // Constructors and destructor
    
        /**
        * ConstructL.
        * 2nd phase constructor.
        */
        void ConstructL();
        
    public: // Functions from base classes

        /**
        * From CEikAppUi, HandleCommandL.
        * Takes care of command handling.
        * @param aCommand Command to be handled.
        */
        virtual void HandleCommandL(TInt aCommand);
		
    private: // Data

        /**
        * iGameView, The application game view
        * Not owned by CZMobileTrackerAppUi object.
        */
        CZMobileTrackerView* iGameView;

        /**
        * iSettingsView, The application settings view
        * Not owned by CZMobileTrackerAppUi object.
        */
        CZMobileTrackerSettingsView* iSettingsView;
	};

#endif // __ZMobileTrackerAPPUI_H__

// End of File
