/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*	  It creates Document, defines UID & defines application properties.
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/


#ifndef __ZMobileTrackerAPP_H__
#define __ZMobileTrackerAPP_H__
#include <aknapp.h>

class CZMobileTrackerApp : public CAknApplication
    {	public: // Functions from base classes
		/**
        * From CApaApplication, OpenIniFileLC.
        * @return the .ini file associated with the application.
        */
        CDictionaryStore* OpenIniFileLC(RFs& aFs) const;
		/**
        * From CApaApplication, AppDllUid.
        * @return Application's UID(KUidNac).
        */
        TUid AppDllUid() const;
    protected: // Functions from base classes
        /**
        * From CApaApplication, CreateDocumentL.
        * Creates CHelloWorldBasicDocument document object. The returned
        * pointer in not owned by the CHelloWorldBasicApplication object.
        * @return A pointer to the created document object.
        */
        CApaDocument* CreateDocumentL();  
    };
#endif // __ZmobileTrackerAPP_H__
