/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*       Initial content was generated by Series 60 Application Wizard.
*	  It creates Document, defines UID & defines application properties.
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/

#include <eikenv.h>
#include "ZMobileTrackerApp.h"
#include "ZMobileTrackerdocument.h"
const TUid KUidNac = { 0x10204950 };	//  This UID is used to differentiate between different applications
// -----------------------------------------------------------------------------
// CZMobileTrackerApp::OpenIniFileLC(RFs& aFs)
// Returns the .ini file associated with the application.
// -----------------------------------------------------------------------------
CDictionaryStore* CZMobileTrackerApp::OpenIniFileLC(RFs& aFs) const
    {	return CEikApplication::OpenIniFileLC(aFs);}
// -----------------------------------------------------------------------------
// CZMobileTrackerApp::AppDllUid()
// Returns application UID.
// -----------------------------------------------------------------------------
TUid CZMobileTrackerApp::AppDllUid() const
    {	return KUidNac;}
// -----------------------------------------------------------------------------
// CZMobileTrackerApp::CreateDocumentL()
// Creates CApaDocument object.
// -----------------------------------------------------------------------------
CApaDocument* CZMobileTrackerApp::CreateDocumentL()
    {	return CZMobileTrackerDocument::NewL (*this);}
// NewApplication()
// Constructs CZMobileTrackerApp.
// Create an application, and return a pointer to it
EXPORT_C CApaApplication* NewApplication()
    {	return new CZMobileTrackerApp;}
// E32Dll()
// Entry point function for Symbian Apps.
GLDEF_C TInt E32Dll( TDllReason )
    {	// DLL entry point, return that everything is ok
		return KErrNone;
    }
