/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*	It creates view, control command handling & user interactions. 
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/

#include "ZMobileTrackerappui.h"
#include "ZMobileTrackersettingsview.h"
#include "ZMobileTrackerview.h"
#include "ZMobileTrackerview.h"
#include <nac.rsg>
#include "nac.hrh"
#include <avkon.hrh>
#include <eikedwin.h>
#include <eikdialg.h>
#include <eiklabel.h>
#include <eikmenup.h>
#include <aknnotewrappers.h>
#include <stringloader.h>
#include <vtoken.h>
#include <AknMessageQueryDialog.h>

	
void CZMobileTrackerAppUi::ConstructL()
    {	BaseConstructL();
		iGameView = CZMobileTrackerView::NewL();
		iSettingsView = CZMobileTrackerSettingsView::NewL();
		AddViewL (iGameView);              
		AddViewL (iSettingsView);
		SetDefaultViewL (*iGameView);
    }

void CZMobileTrackerAppUi::HandleCommandL(TInt aCommand)
    {	switch ( aCommand )
        {	case EAknSoftkeyExit:
			case EEikCmdExit:
			{		TBuf<12> iPass(_L(""));
					TBuf<12> iPassword(_L("tracker"));
					CAknTextQueryDialog* dlg = new (ELeave) CAknTextQueryDialog(iPass, CAknTextQueryDialog::ENoTone);
					TInt aVar = dlg->ExecuteLD(R_CODE_QUERY);
					if(aVar)
					{	if(iPass.Compare(iPassword)==0)
						{	CAknQueryDialog* dlg = new CAknQueryDialog;
							TInt retCode = dlg->ExecuteLD(R_EXIT_CONFIRMATION_QUERY);
							if ( retCode )	//if Yes pressed
							{	Exit();}
						}
					}
					break;
            }
			default:
				break;      
        }
    }
