/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*     It creates AppUI & takes care of data model of application.
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/

#include "ZMobileTrackerappui.h"
#include "ZMobileTrackerdocument.h"
#include "ZMobileTrackerinformationandsettings.h"
CZMobileTrackerDocument* CZMobileTrackerDocument::NewL(
    CEikApplication& aApp)
    {
    CZMobileTrackerDocument* self = new (ELeave) CZMobileTrackerDocument (aApp);
    CleanupStack::PushL (self);
    self->ConstructL();
    CleanupStack::Pop();

    return self;
    }
CZMobileTrackerDocument::CZMobileTrackerDocument(CEikApplication& aApp) :
    CAknDocument(aApp)    
    {    }
void CZMobileTrackerDocument::ConstructL()
    {
    iSettings = new (ELeave) CZMobileTrackerInformationAndSettings;
	CDictionaryStore* iniFile = Application()->OpenIniFileLC (CEikonEnv::Static()->FsSession());
	if (iniFile->IsPresentL (Application()->AppDllUid()))
        {
        RDictionaryReadStream stream;
        stream.OpenLC (*iniFile, Application()->AppDllUid());	
        stream >> *iSettings;
        CleanupStack::PopAndDestroy();
        }
    CleanupStack::PopAndDestroy (iniFile);
    /*if (iSettings->HumanTypeCross())
        {
        iEngine = CZMobileTrackerEngine::NewL (CZMobileTrackerEngine::ECross);
        }
    else
        {*/
        iEngine = CZMobileTrackerEngine::NewL (CZMobileTrackerEngine::ENought);
        /*/}

    if (!iSettings->HumanPlayFirst())
        {
        MakeComputerMove();
        }
		*/
    }
CZMobileTrackerDocument::~CZMobileTrackerDocument()
    {
    delete iEngine;
    delete iSettings;
    }
CEikAppUi* CZMobileTrackerDocument::CreateAppUiL()
    {
    return new (ELeave) CZMobileTrackerAppUi;
    }
void CZMobileTrackerDocument::SetObserver (
    CZMobileTrackerEngine::MObserver* aObserver)
    {
    iEngine->SetObserver (aObserver);
    }

void CZMobileTrackerDocument::NewGame()
    {
    if (iSettings->HumanTypeCross())
        {
        iEngine->StartNewGame (CZMobileTrackerEngine::ECross);
        }
    else
        {
        iEngine->StartNewGame (CZMobileTrackerEngine::ENought);
        }

    if (!iSettings->HumanPlayFirst())
        {
        MakeComputerMove();
        }
    }

TBool CZMobileTrackerDocument::CanMove() const
    {
    return iEngine->CanMove();
    }

TBool CZMobileTrackerDocument::MakeHumanMove(TInt aRow, TInt aColumn)
    {
    return iEngine->MakeHumanMove (aRow, aColumn);
    }

TBool CZMobileTrackerDocument::MakeComputerMove()
    {
    return iEngine->MakeComputerMove();
    }

CZMobileTrackerInformationAndSettings& 
    CZMobileTrackerDocument::InformationAndSettings()
    {	return *iSettings;}
const CZMobileTrackerInformationAndSettings& 
    CZMobileTrackerDocument::InformationAndSettings() const
    {	return *iSettings;}
void CZMobileTrackerDocument::SaveSettingsAndInformationL()
    {
    CDictionaryStore* iniFile = Application()->OpenIniFileLC (CEikonEnv::Static()->FsSession());
	
    iniFile->RemoveL (Application()->AppDllUid());

    RDictionaryWriteStream stream;

    stream.AssignLC (*iniFile, Application()->AppDllUid());
    stream << *iSettings;
    stream.CommitL();
    CleanupStack::PopAndDestroy(); // stream

    iniFile->Commit();

    CleanupStack::PopAndDestroy (iniFile);
    }


