/*
* ============================================================================
*  Part of  : Mobile Tracker
*  Created  : 12.05.2009 by Kishoj, Meena
*  Implementation notes:
*     Initial content was generated by Series 60 Application Wizard.
*	It contains display of data on the screen, manages controls that are visible
*  Version  : 1.062
*  Copyright: 062-BCT  Mobile Tracker Group
* ============================================================================
*/



// INCLUDE FILES
#include <aknviewappui.h>
#include <AknUtils.h>
#include <nac.rsg>

#include "ZMobileTrackercontainer.h"
#include "ZMobileTrackerdocument.h"
#include "ZMobileTrackerinformationandsettings.h"
#include "ZMobileTrackerview.h"


// ============================ MEMBER FUNCTIONS ===============================

// -----------------------------------------------------------------------------
// CAknExGridContainer::NewL()
// Two-phased constructor.
// -----------------------------------------------------------------------------
//

CZMobileTrackerContainer* CZMobileTrackerContainer::NewL(
    const TRect& aRect, CZMobileTrackerView& aView, TInt aCursorRow, TInt aCursorColumn)
    {
    CZMobileTrackerContainer *self = new (ELeave) CZMobileTrackerContainer(
        aView, aCursorRow, aCursorColumn);
    CleanupStack::PushL (self);
    self->ConstructL (aRect);
    CleanupStack::Pop();
    return self;
    }

// ----------------------------------------------------------------------------
// CZMobileTrackerContainer::CZMobileTrackerContainer()
// Default constructor.
// ----------------------------------------------------------------------------
//
CZMobileTrackerContainer::CZMobileTrackerContainer(
    CZMobileTrackerView& aView, TInt aCursorRow, TInt aCursorColumn) :
    iView (aView), iCursorRow (aCursorRow), iCursorColumn (aCursorColumn)
    {
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::ConstructL()
// Symbian 2nd phase constructor can leave.
// -----------------------------------------------------------------------------
//
void CZMobileTrackerContainer::ConstructL(const TRect& aRect)
    {
    CreateWindowL();
    SetRect(aRect);
	SetExtentToWholeScreen();   //for full screen 
    ActivateL();
    HandleBoardReset();
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::~CZMobileTrackerContainer()
// Destructor.
// -----------------------------------------------------------------------------
//
CZMobileTrackerContainer::~CZMobileTrackerContainer()
    {
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::SizeChanged()
// Called by framework when the view size is changed.
// -----------------------------------------------------------------------------
//
void CZMobileTrackerContainer::SizeChanged()
    {
    }

// ---------------------------------------------------------
// CZMobileTrackerSettingListbox::HandleResourceChange()
// Called by framework when layout is changed.
// ---------------------------------------------------------
//
void CZMobileTrackerContainer::HandleResourceChange(TInt aType)
    {
    
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::CountComponentControls()
// Returns number of components.
// -----------------------------------------------------------------------------
//
TInt CZMobileTrackerContainer::CountComponentControls() const
    {
    return 0;
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::ComponentControl()
// Returns pointer to a particular component.
// -----------------------------------------------------------------------------
//
CCoeControl* CZMobileTrackerContainer::ComponentControl (TInt /*aIndex*/) const
    {
    return NULL;	
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::Draw()
// Draw function.
// -----------------------------------------------------------------------------
//
void CZMobileTrackerContainer::Draw(const TRect& aRect) const
    {
    CWindowGc& gc = SystemGc();
	gc.SetPenColor(KRgbRed); 
    gc.SetPenStyle (CGraphicsContext::ESolidPen);
	gc.SetBrushColor(KRgbBlue);
    gc.SetBrushStyle (CGraphicsContext::ESolidBrush);
    gc.DrawRect (aRect);

	TBuf<30> tempStr;
	gc.SetPenColor(KRgbRed); 
    gc.SetPenStyle (CGraphicsContext::ESolidPen);

	gc.SetBrushColor( KRgbYellow );
	gc.SetBrushStyle( CGraphicsContext::ESolidBrush );
	gc.UseFont(CEikonEnv::Static()->AnnotationFont());
	CEikonEnv::Static()->ReadResource(tempStr, RS_TEXT1);
	gc.DrawText(tempStr, TRect(25, 20, 145, 60), 25, CGraphicsContext::ECenter);


	gc.SetBrushColor( KRgbYellow );
	gc.SetBrushStyle( CGraphicsContext::ESolidBrush );
	gc.UseFont(CEikonEnv::Static()->AnnotationFont());
	CEikonEnv::Static()->ReadResource(tempStr, RS_TEXT_MENU);
	gc.DrawText(tempStr, TRect(05, 170, 45, 200), 20, CGraphicsContext::ECenter);

	gc.SetBrushColor( KRgbYellow );
	gc.SetBrushStyle( CGraphicsContext::ESolidBrush );
	gc.UseFont(CEikonEnv::Static()->AnnotationFont());
	CEikonEnv::Static()->ReadResource(tempStr, RS_TEXT_EXIT);
	gc.DrawText(tempStr, TRect(130, 170, 170, 200), 20, CGraphicsContext::ECenter);
    }

// ---------------------------------------------------------------------------
// CZMobileTrackerContainer::OfferKeyEventL()
// Handles keyevents.
// ---------------------------------------------------------------------------
//
TKeyResponse CZMobileTrackerContainer::OfferKeyEventL(
    const TKeyEvent& aKeyEvent, TEventCode aType)
    {
        return EKeyWasNotConsumed;
       
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::HandleMove()
// 
// -----------------------------------------------------------------------------
//
void CZMobileTrackerContainer::HandleMove(TPlayer /*aPlayer*/, TUint /*aRow*/,
    TUint /*aColumn*/)
    {
    
    }

// -----------------------------------------------------------------------------
// CZMobileTrackerContainer::HandleWinner()
// 
// -----------------------------------------------------------------------------
//
void CZMobileTrackerContainer::HandleWinner(TBool aHumanWins, TUint aXRow,
    TUint aXColumn, TUint aZRow, TUint aZColumn)
    {
    CZMobileTrackerDocument* document = static_cast<
         CZMobileTrackerDocument*> (iView.AppUi()->Document());

    
    }



void CZMobileTrackerContainer::HandleBoardReset()
   {
    
    }


